### ISSUE TITLE
Use Path Module to Resolve Absolute Path

### ISSUE THREAD

**Issue by APratham** [PCCoE-Hacktoberfest-21/qwiklabs-leader-board#3]
We need to resolve absolute path also 

https://github.com/PCCoE-Hacktoberfest-21/qwiklabs-leader-board/blob/9c8c17479243bd9edf118417b9981430c8042396/crawler/index.js#L20

https://github.com/PCCoE-Hacktoberfest-21/qwiklabs-leader-board/blob/9c8c17479243bd9edf118417b9981430c8042396/crawler/index.js#L34

**Comment by jhasuraj01** [comment]
okay! I will correct it.
